### ISSUE TITLE
TUXML version: Unable to find the missing package(s)

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#136]
python3 kernel_generator.py --tiny --linux4_version 8.1 --dev 1
```
00:00:13 [2019-03-29 09:20:50 CET] [__linux_config_generator] Tiny config with preset values here : /TuxML/compilation/x64.config .
00:00:18 [2019-03-29 09:20:55 CET] [__compile] Compilation in progress
00:00:21 [2019-03-29 09:20:58 CET] [__compile] Compilation failed, exit status : 2.
00:00:21 [2019-03-29 09:20:58 CET] [__log_analyser] Analysing /TuxML/logs/stderr.log
00:00:21 [2019-03-29 09:20:58 CET] [__log_analyser] Unable to find the missing package(s).
00:00:21 [2019-03-29 09:20:58 CET] [__do_a_compilation] Unable to compile in 00:00:03 (installation_time = 00:00:00)
00:00:21 [2019-03-29 09:20:58 CET] [insert_result_into_database] Sending result to database.
00:00:21 [2019-03-29 09:20:58 CET] [insert_result_into_database] Successfully send result with cid : 76
```

python3 kernel_generator.py --tiny --linux4_version 8.1 --dev 1
```
00:00:07 [2019-03-29 09:21:44 CET] [__linux_config_generator] Tiny config with preset values here : /TuxML/compilation/x64.config .
00:00:10 [2019-03-29 09:21:47 CET] [__compile] Compilation in progress
00:00:12 [2019-03-29 09:21:49 CET] [__compile] Compilation failed, exit status : 2.
00:00:12 [2019-03-29 09:21:49 CET] [__log_analyser] Analysing /TuxML/logs/stderr.log
00:00:12 [2019-03-29 09:21:49 CET] [__log_analyser] Unable to find the missing package(s).
00:00:12 [2019-03-29 09:21:49 CET] [__do_a_compilation] Unable to compile in 00:00:02 (installation_time = 00:00:00)
00:00:12 [2019-03-29 09:21:49 CET] [insert_result_into_database] Sending result to database.
00:00:12 [2019-03-29 09:21:49 CET] [insert_result_into_database] Successfully send result with cid : 77
```

same with 7.1
```
00:00:08 [2019-03-29 09:25:26 CET] [__linux_config_generator] Tiny config with preset values here : /TuxML/compilation/x64.config .
00:00:11 [2019-03-29 09:25:29 CET] [__compile] Compilation in progress
00:00:13 [2019-03-29 09:25:31 CET] [__compile] Compilation failed, exit status : 2.
00:00:13 [2019-03-29 09:25:31 CET] [__log_analyser] Analysing /TuxML/logs/stderr.log
00:00:13 [2019-03-29 09:25:31 CET] [__log_analyser] Unable to find the missing package(s).
00:00:13 [2019-03-29 09:25:31 CET] [__do_a_compilation] Unable to compile in 00:00:02 (installation_time = 00:00:00)
00:00:13 [2019-03-29 09:25:31 CET] [insert_result_into_database] Sending result to database.
00:00:13 [2019-03-29 09:25:31 CET] [insert_result_into_database] Successfully send result with cid : 78
```

It works with version 9.1 !!

side note: it seems versioning support cannot be activated without having the "core" Docker images before (ie I clean my Docker images, and then directly use linux4_version: it fails; when I clean my Docker images, launch --tiny on the default version, and then linux4_version it works!)

**Comment by mipicard** [comment]
I look into stderr log file for cid 76 : 
```
scripts/mod/empty.c:1:0: error: code model kernel does not support PIC mode
 /* empty file to figure out endianness / word size */
 
make[2]: *** [scripts/mod/empty.o] Error 1
make[1]: *** [scripts/mod] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [scripts] Error 2
make: *** Waiting for unfinished jobs....
```

for the side note, it looks like some typo could be present, i will look into it.

**Comment by FAMILIAR-project** [comment]
Hum maybe related to https://askubuntu.com/questions/851433/kernel-doesnt-support-pic-mode-for-compiling and what @Luisky explained to us about gcc-hell 
We have to validate this assumption and explicitly warn that below version 4.9, we're unable to support it. 
(Or find a workaround which is not so straightforward to implement I think)

**Comment by FAMILIAR-project** [comment]
TODO: update the documentation to state that we only support kernel version >= 4.9
